#!/bin/bash

target=$1
top_port=13999
low_port=9000
mid_port=$(( (($top_port - $low_port)/2) + $low_port ))
port_range=$(( $top_port - $low_port ))

while [ $port_range -gt 5 ]; do
	echo -ne "Testing $mid_port.....               "\\r
	result=$(timeout --foreground --signal=9 20 ssh -q -o StrictHostKeyChecking=No $target -p $mid_port)

	if [[ $result =~ Higher ]]; then
		echo -ne "Target port is lower than $mid_port."\\r
		top_port=$mid_port
		sleep 1
	elif [[ $result =~ Lower ]]; then
		echo -ne "Target port is higher than $mid_port."\\r
		low_port=$mid_port
		sleep 1
	else
		echo -e "\n\nThe real SSH service is on port $mid_port"
		exit 0
fi
	mid_port=$(( (($top_port - $low_port)/2) + $low_port ))
	port_range=$(( $top_port - $low_port ))
done

for i in range {0..5}; do
	port=$(( $low_port + $i ))
	echo -ne "Testing $port.....               "\\r
	result=$(timeout --foreground --signal=9 20 ssh -q -o StrictHostKeyChecking=No $target -p $port)
	
#	echo "DEBUG RESULT: $result"
# NOTE - the ciphertext poem is in $result here when correct port is found, and could be used to decode the Secret
# for display in the exit message

	if [[ $result =~ Higher ]] || [[ $result =~ Lower ]]; then
	        continue
	else
		echo -e "\n\nThe real SSH service is on port $port"
		exit 0
	fi
done
